remote_theme: just-the-docs/just-the-docs
title: Anima Prime Versione Italiana
exclude: [_build, glossario, sorgente]

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3